name: Composition Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  composition-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install up
        uses: upbound/action-up@53fe6395637d884c80d2bbc8c2d75d0ece776ced # v1
        with:
          skip-login: true

      - name: Build project
        run: up project build

      - name: Run composition tests
        run: up test run tests/*
